### ISSUE TITLE
Nested sektions alignment thoughts

### ISSUE THREAD

**Issue by eri-trabiccolo** [presscustomizr/nimble-builder#25]
Take a look at the screenshot:
<img width="596" alt="2018-06-11_9-08-56" src="https://user-images.githubusercontent.com/7689242/41217710-01c4618c-6d59-11e8-89a9-758f321ecc82.png">

It's a column with an image placeholder, then with the red background you can see a nested sektion of two columns.
Do we really want this kind of _mixed vertical_ alignment? Meaning, you can see that the right/left edges of the top image (column with orange background) are not aligned with the left edge of the first column text (yellow background) and the right edge of the second column image (blue background).

1) The nested sektion should reset its parent column padding
2) The nested sektion  `.sek-sektion-inner` should not have a right/left padding of 15px (I'm not sure about this padding overall, see:  https://github.com/presscustomizr/nimble-builder/issues/24 )

Here's the screenshot with the 1) and 2) applied
<img width="591" alt="2018-06-11_9-27-17" src="https://user-images.githubusercontent.com/7689242/41217952-c93704f4-6d59-11e8-956c-e02ce62be1db.png">

CSS:
```css
[data-sek-is-nested="true"] .sek-container-fluid, 
[data-sek-is-nested="true"] .sek-sektion-inner {
    padding-right: 0;
    padding-left: 0;
}
```

What do you think?
