### ISSUE TITLE
.sek-hidden-on-tablets and .sek-hidden-on-mobiles breakpoints are wrong, with overlapping points

### ISSUE THREAD

**Issue by eri-trabiccolo** [presscustomizr/nimble-builder#551]
see:
https://github.com/presscustomizr/nimble-builder/blob/v1.9.12/assets/front/scss/sek-base.scss#L139-L148

The way those "hiding" rules are done right now might create some "blind" spots where nothing is visible.

How to reproduce this:
1) create a module and make it visible only in desktops
2) create a module and make it visible only in tablets and mobiles
3) stretch the window till reaching 768px
You'll see that between 768px and 767px (included) both the modules created above are not visible.

The actual visibility code should be:

```css
/* LEVEL VISIBILITY BY DEVICE */
@media (min-width:768px){
  [data-sek-level="location"] .sek-hidden-on-desktops { display: none; }
}
@media (min-width:576px) and (max-width:767px){
  [data-sek-level="location"] .sek-hidden-on-tablets { display: none; }
}
@media (max-width:575px){
  [data-sek-level="location"] .sek-hidden-on-mobiles { display: none; }
}
```
right?

reported: 
https://wordpress.org/support/topic/header-responsiveness-3/
