### ISSUE TITLE
[button module] custom text color on hover should also be applied to :focus

### ISSUE THREAD

**Issue by Nikeo** [presscustomizr/nimble-builder#849]
```CSS
.nb-loc .sek-row [data-sek-id="__nimble__9bfb8337772c"] .sek-module-inner .sek-btn:hover {
    color: #db8104;
}
```
