### ISSUE TITLE
[button module] add an option to prevent word break

### ISSUE THREAD

**Issue by Nikeo** [presscustomizr/nimble-builder#852]
For the moment here's the default btn style

```CSS
.sek-module .sek-module-inner .sek-btn {
    display: inline-block;
    font-weight: 400;
    line-height: 1.25em;
    text-align: center;
    white-space: normal;
    word-break: break-all;
    vertical-align: middle;
    user-select: none;
    border: 1px solid transparent;
    padding: .5em 1em;
    border-radius: 2px;
    border-width: 2px;
    border-style: solid;
    font-size: 1em;
    cursor: pointer;
    text-decoration: none;
    text-transform: none;
    -webkit-transition: all .2s ease-in-out;
    -o-transition: all .2s ease-in-out;
    transition: all .2s ease-in-out;
}
```
