### ISSUE TITLE
Input dynamic CSS selectors, how to?

### ISSUE THREAD

**Issue by eri-trabiccolo** [presscustomizr/nimble-builder#97]
I've found the the input css_selectors param is appended to the module css_selectors, if any.
Example for the divider:
1) The whole module CSS dyn rules should be applied to the .sek-divider element, so I set  the module  `css_selectors` param to be `array( '.sek-divider' )`
2) I then want the h_alignment_css property to be applied to the `.sek-module-inner` (which is the `.sek-divider` parent).

Customizing:
a) I apply a width of 50% to the divider
b) I choose the left alignment
 
Expected CSS result:
```css
[data-sek-id="__nimble__e98120111195e4d1f5c611a6"] .sek-divider{width:50%;}
[data-sek-id="__nimble__e98120111195e4d1f5c611a6"] .sek-module-inner{text-align:left;}
```

Current CSS result:
```css
[data-sek-id="__nimble__e98120111195e4d1f5c611a6"] .sek-divider{width:50%;}
[data-sek-id="__nimble__e98120111195e4d1f5c611a6"] .sek-divider .sek-module-inner{text-align:left;}
```
